spring.application.name=SpringH2Hello

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# This property ensures that any SQL scripts (like schema.sql or data.sql) are run after the JPA schema is created or updated.
# It is useful when using in-memory databases (like H2) to avoid errors from scripts running before tables exist.
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# http://localhost:8070/api/users
server.port=8070
